//===========================================================================
// 
// |cffFF8000Bleach Kidou Wars 5.00|r
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Tue Apr 06 11:33:54 2010
//   Map Author: Kisame
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//*******************************************     udg_SP_Skip                = 0
    unit array              udg_SP_Caster
    location array          udg_SP_Point
    real array              udg_SP_Distance
    real array              udg_SP_Speed
    real array              udg_SP_Angle
    integer array           udg_SP_Spam
    integer                 udg_SP                     = 0
    boolean array           udg_HN_Off
    integer                 udg_HN_Times               = 0
    integer                 udg_HN_Skip                = 0
dg_Ban_Group
    group array             udg_Ban_ExGroup
    unit array              udg_Ban_Dummy3
    integer                 udg_Kuro_Skip              = 0
    integer                 udg_Kuro_Times             = 0
    boolean array           udg_Kuro_Off
    unit array              udg_Kuro_Caster
    unit array              udg_Kuro_Dummy
    integer array           udg_Kuro_Equation
    real array              udg_Kuro_Duration
    real array              udg_Kuro_Minus
    group array                 udg_Goc_Dummy              = null
    unit                    udg_Goc_BlockDummy         = null
    unit                    udg_D_Caster               = null
    location array          udg_D_Point
    real                    udg_D_Aoe                  = 0
    integer                 udg_D_Level                = 0
    unit                    udg_D_Dummy                = null
    group                   udg_D_Group                = null
    integer                 udg_D                   2             = null
    group                   udg_TempGroup1             = null
    group                   udg_DamageGroup            = null
    player                  udg_ProjectileDeathOwner   = null
    unit                    udg_ProjectileDeath        = null
    location                udg_TempPoint6             = null
    location                udg_Ring                   = null
    unit                    udg_Caster                 = null
    location                udg_TempLoc1            gg_rct_Fortwars            = null
    rect                    gg_rct_Arena               = null
    rect                    gg_rct_Seiretei_Flag_Zone  = null
    rect                    gg_rct_Arrancar_Flag_Zone  = null
    rect                    gg_rct_Telepad             = null
    rect                    gg_rct_Seireitei_base      = null
    rect                    gg_rct_Arrancar_Base       = null
    rect                    gg_rct_Shopping_Area       = null
    rect                    gg_rcg_trg_Raikoho_Loop        = null
    trigger                 gg_trg_Hiyuri_Cast         = null
    trigger                 gg_trg_Hiyuri_Loop         = null
    trigger                 gg_trg_DamageShunpo        = null
    trigger                 gg_trg_Damage_Shunpo_Loop  = null
    trigger                 gg_trg_Cast                = null
    trigger                 gg_trg_Kyoumon_Death       = null
    trigger                 gg_trg_ShunpoCast          = null
    trigger                 gg_trg_Sh= null
    trigger                 gg_trg_Sample_Explosion_Spell = null
    trigger                 gg_trg_Sample_Warstomp_Spell = null
    trigger                 gg_trg_Projectile_System   = null
    trigger                 gg_trg_Projectile_Death_System = null
    trigger                 gg_trg_Effects_Loss_System = null
    trigger                 gg_trg_Release_Effects_System = null
    trigger                 gg_trg_Effectgroupcheck    = null
    trigger                 gg_trg_Summons_Remove     gg_trg_Cero_Oscuras_cast   = null
    trigger                 gg_trg_Lanza_del_Relampago_cast = null
    trigger                 gg_trg_Minazuki_Release    = null
    trigger                 gg_trg_Minazuki_Follow     = null
    trigger                 gg_trg_Minazuki_Land       = null
    trigger                 gg_trg_Jizou_Release       = null
    trigger                 gg_trg_Jizou_Poison        = null
    trigger                 gg_trg_Jizou_Charge        = null
    trigger                 dloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_BB_Distance[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_BB_Angle[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_BB_Speed[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_BB_Spam[i] = 0
        set i = i + 1
    endloop

    set i = 0 i = 0
    loop
        exitwhen (i > 1)
        set udg_SP_Angle[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_SP_Spam[i] = 0
        set i = i + 1
    endloop

    set udg_SP = 0
    set i = 0
    loop
        exitwhen (i > 1)
        set udg_HN_Off[i] = false
        set i = i + 1
    endloop

    set udg_HN_Times = 0
    set udg_HN_Skip = 0
    set i = 0
    loop
        exitwhen (i > 1)
        set udg_HN_Equation[i]oop
        exitwhen (i > 1)
        set udg_Shin_Distance[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_Shin_Angle[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_Shin_Speed[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_Shin_Equation[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
       loop
        exitwhen (i > 1)
        set udg_Rope_Damage[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_Rope_ExGroup[i] = CreateGroup()
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_Rope_Group[i] = CreateGroup()
        set i = i + 1
    endloop

    set udg_Cero_Skip = 0
    set udg_Cero_Times = 0
    set i = 0
    loop
        exitwhen (i > 1)
        set udg_Cero_Off endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_KB_SpecificSpeed[i] = 0
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_KB_Effects_1[i] = ""
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_KB_Effects_2[i] = ""
        set i = i + 1
    endloop

    set i = 0
    loop
        exitwhen (i > 1)
        set udg_KB_DestroyTrees[i] = false
        set i = i + 1 CreateGroup()
    set udg_MinazukiGroup2 = CreateGroup()
    set udg_JizouGroup = CreateGroup()
    set udg_JizouDamGroup1 = CreateGroup()
    set udg_TengenGroup = CreateGroup()
    set udg_TengenDamGroup1 = CreateGroup()
    set udg_TempNum = 0
    set udg_CastGroup = CreateGroup()
    set udg_JizouGroup2 = CreateGroup()
    set udg_EyeDamGroup = CreateGroup()
    set udg_BallPowerGroup = CreateGroup()
    set udg_GrowthGroup = CreateGroup()
    set udg_IttoKasoGroup = CreateGroup()
endfunctd_HealingWave01, "HealingWaveTarget" )
    call SetSoundDuration( gg_snd_HealingWave01, 2229 )
    set gg_snd_Kudakero = CreateSound( "war3mapImported\\Kudakero.mp3", false, false, false, 10, 10, "" )
    call SetSoundDuration( gg_snd_Kudakero, 575 )
    call SetSoundChannel( gg_snd_Kudakero, 0 )
    call SetSoundVolume( gg_snd_Kudakero, 127 )
    call SetSoundPitch( gg_snd_Kudakero, 1.0 )
    set gg_snd_Yamamoto_Shikai___Ryujin_Jaka = CreateSound( "war3mapImported\\Yamamoto Shikai - Ryujin Jaka.mp3"layer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'ncop', -2816.0, 2880.0, 270.000 )
    set u = CreateUnit( p, 'h02J', -2496.0, -2944.0, 270.000 )
endfunction

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer uni unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'ncop', -3200.0, 2368.0, 270.000 )
    set u = CreateUnit( p, 'h02J', -2496.0, -3968.0, 270.000 )
endfunction

//===========================================================================
function CreateNeutralHostileBuildings takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_AGGRESSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life
u = CreateUnit( p, 'h003', -5233.3, -8089.6, 99.616 )
    set u = CreateUnit( p, 'h003', -5337.9, -9216.6, 51.593 )
    set u = CreateUnit( p, 'h003', -4580.8, -9627.8, 127.632 )
    set u = CreateUnit( p, 'h003', -5432.2, -9987.4, 276.381 )
    set u = CreateUnit( p, 'h003', -5829.9, -8641.2, 161.218 )
    set u = CreateUnit( p, 'h003', -5495.1, -7448.5, 348.673 )
    set u = CreateUnit( p, 'h002', 222.2, -5391.3, 353.880 )
    set u = CreateUnit( p, 'h002', -268.8, -5404.7, 95.243 )
    set u = CrE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'ncp2', -4512.0, 3744.0, 270.000 )
    set u = CreateUnit( p, 'ncp2', -4832.0, 3744.0, 270.000 )
    set u = CreateUnit( p, 'ncp3', 2752.0, -3136.0, 270.000 )
    set u = CreateUnit( p, 'ncp3', 2752.0, 3712.0, 270.000 )
    set u = CreateUnit( p, 'nwgt', -3584.0, -2816.0, 270.000 )
    set u = CreateUnit( p, 'n000', -4480.0, -3776.0, 270.000 )
    set u = CreateUnit( p, 'n004', -4480._Arena = Rect( 736.0, -3552.0, 5120.0, 4224.0 )
    set gg_rct_Region_009 = Rect( -1504.0, -2112.0, 512.0, 3648.0 )
    set gg_rct_Region_010 = Rect( -5312.0, -2112.0, -1248.0, 576.0 )
    set gg_rct_HeroSelect = Rect( -3456.0, 2176.0, -2560.0, 3040.0 )
    set gg_rct_Region_012 = Rect( -6112.0, -10240.0, 6112.0, -6624.0 )
    set gg_rct_Region_013 = Rect( -1600.0, -6624.0, 6080.0, -4960.0 )
    set gg_rct_Big_Arena = Rect( -4288.0, 3648.0, -4096.0, 3840.0 )
    set gg_rct_Region_015 = Rect( -5024.0,, -3597.6, -4329.5, 0.0 )

    set gg_cam_Camera_004 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_ROTATION, 90.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_ANGLE_OF_ATTACK, 304.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_TARGET_DISTANCE, 1650.0, 0.0 )
    call CameraSetupSetField( gg_cam_Camera_004, CAMERA_FIELD_ROLL, 0.0, 0.0 ========================
function Trig_DamageShunpo_Func001C takes nothing returns boolean
    if ( ( GetSpellAbilityId() == 'A030' ) ) then
        return true
    endif
    if ( ( GetSpellAbilityId() == 'A026' ) ) then
        return true
    endif
    return false
endfunction

function Trig_DamageShunpo_Conditions takes nothing returns boolean
    if ( not Trig_DamageShunpo_Func001C() ) then
        return false
    endif
    return true
endfunction

function Trig_DamageShunpo_Func002C 
    endif
    return true
endfunction

function Trig_Damage_Shunpo_Loop_Func001Func001Func001Func006A takes nothing returns nothing
    if ( Trig_Damage_Shunpo_Loop_Func001Func001Func001Func006Func001C() ) then
        call UnitDamageTargetBJ( udg_HN_Caster[udg_HN], GetEnumUnit(), 50.00, ATTACK_TYPE_HERO, DAMAGE_TYPE_NORMAL )
        call GroupAddUnitSimple( GetEnumUnit(), udg_HN_ExGroup[udg_HN] )
    else
        call UnitDamageTargetBJ( udg_HN_Caster[udg_HN], GetEnumUnit(), 35.00, ATTACK_TYPE_HE_HN + 1
    endloop
endfunction

//===========================================================================
function InitTrig_Damage_Shunpo_Loop takes nothing returns nothing
    set gg_trg_Damage_Shunpo_Loop = CreateTrigger(  )
    call DisableTrigger( gg_trg_Damage_Shunpo_Loop )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Damage_Shunpo_Loop, 0.02 )
    call TriggerAddAction( gg_trg_Damage_Shunpo_Loop, function Trig_Damage_Shunpo_Loop_Actions )
endfunction

//===========================================================
// Trigger: Shunpo Loop
//===========================================================================
function Trig_Shunpo_Loop_Func001Func001Func001Func005Func001002003001 takes nothing returns boolean
    return ( IsUnitAlly(GetFilterUnit(), GetOwningPlayer(udg_SP_Caster[udg_SP])) == false )
endfunction

function Trig_Shunpo_Loop_Func001Func001Func001Func005Func001002003002 takes nothing returns boolean
    return ( IsUnitInGroup(GetFilterUnit(), udg_SDG) == fals            set udg_SP_Skip = ( udg_SP_Skip - 1 )
                set udg_SP_Off[udg_SP] = false
                call SetUnitPathing( udg_SP_Caster[udg_SP], true )
                call SetUnitVertexColorBJ( udg_SP_Caster[udg_SP], 100, 100, 100, 0.00 )
                if ( Trig_Shunpo_Loop_Func001Func001Func001Func017C() ) then
                    set udg_SP_Times = 0
                    call DisableTrigger( gg_trg_Shunpo_Loop )
                else
                endif
            else
          Can_Times] = 5000.00
    set udg_Can_Angle[udg_Can_Times] = AngleBetweenPoints(udg_Can_Point[0], udg_Can_Point[1])
    set udg_Can_Speed[udg_Can_Times] = 20.00
    set udg_Can_Spam[udg_Can_Times] = 0
    set udg_Can_Aoe[udg_Can_Times] = 100.00
    set udg_Can_Damage[udg_Can_Times] = 50
    // Unit
    call CreateNUnitsAtLoc( 1, 'h00A', GetOwningPlayer(udg_Can_Caster[udg_Can_Times]), udg_Can_Point[0], udg_Can_Angle[udg_Can_Times] )
    set udg_Can_Dummy[udg_Can_Times] = GetLastCreatedUnit()
    // L            set udg_Can_Point[2] = GetUnitLoc(udg_Can_Dummy[udg_Can])
                set udg_Can_Group[udg_Can] = GetUnitsInRangeOfLocMatching(150.00, udg_Can_Point[2], Condition(function Trig_Kido_Loop_Func001Func001Func001Func016002003))
                call ForGroupBJ( udg_Can_Group[udg_Can], function Trig_Kido_Loop_Func001Func001Func001Func017A )
                call AddSpecialEffectLocBJ( udg_Can_Point[2], "war3mapImported\\NuclearExplosion.mdx" )
                call DestroyEffectBJ( GetLastCreatShin_Distance[udg_Shin_Times] = 1000.00
    set udg_Shin_Angle[udg_Shin_Times] = AngleBetweenPoints(udg_Shin_Point[0], udg_Shin_Point[1])
    set udg_Shin_Speed[udg_Shin_Times] = 60.00
    // Dummy
    call PlaySoundAtPointBJ( gg_snd_Byakurai, 100, udg_Shin_Point[0], 0 )
    call CreateNUnitsAtLoc( 1, 'h00J', GetOwningPlayer(udg_Shin_Caster[udg_Shin_Times]), udg_Shin_Point[0], udg_Shin_Angle[udg_Shin_Times] )
    set udg_Shin_Dummy[udg_Shin_Times] = GetLastCreatedUnit()
    // Leak Removal
    call nction Trig_Byakurai_Loop_Actions takes nothing returns nothing
    set udg_Shin = 1
    loop
        exitwhen udg_Shin > udg_Shin_Times
        if ( Trig_Byakurai_Loop_Func001Func001C() ) then
            if ( Trig_Byakurai_Loop_Func001Func001Func001C() ) then
                set udg_Shin_Skip = ( udg_Shin_Skip - 1 )
                set udg_Shin_Off[udg_Shin] = false
                set udg_Shin_Point[2] = GetUnitLoc(udg_Shin_Dummy[udg_Shin])
                set udg_Shin_DamGroup[udg_Shin] = GetUn) ) then
        call EnableTrigger( gg_trg_Kei_Loop )
    else
    endif
    set udg_Kei_Times = ( udg_Kei_Times + 1 )
    set udg_Kei_Skip = ( udg_Kei_Skip + 1 )
    set udg_Kei_Off[udg_Kei_Times] = true
    // Setup
    set udg_Kei_Caster[udg_Kei_Times] = GetSpellAbilityUnit()
    set udg_Kei_Point[0] = GetUnitLoc(udg_Kei_Caster[udg_Kei_Times])
    set udg_Kei_Point[1] = GetSpellTargetLoc()
    set udg_Kei_Equation[udg_Kei_Times] = ( GetUnitAbilityLevelSwapped('A00Q', udg_Kei_Caster[udg_Kei_TiAnd( Trig_Kei_Loop_Func001Func001Func001Func017002003001(), Trig_Kei_Loop_Func001Func001Func001Func017002003002() )
endfunction

function Trig_Kei_Loop_Func001Func001Func001Func018A takes nothing returns nothing
    call SetUnitLifeBJ( GetEnumUnit(), ( GetUnitStateSwap(UNIT_STATE_LIFE, GetEnumUnit()) + 15.00 ) )
    call GroupClear( udg_Kei_HealGroup[udg_Kei] )
endfunction

function Trig_Kei_Loop_Func001Func001Func001Func020C takes nothing returns boolean
    if ( not ( udg_Kei_Skip == 0 ) ) then

        return false
    endif
    return true
endfunction

function Trig_Control_Swap_Actions takes nothing returns nothing
    if ( Trig_Control_Swap_Func001C() ) then
        call SetUnitOwner( gg_unit_hpea_0020, Player(1), true )
    else
    endif
endfunction

//===========================================================================
function InitTrig_Control_Swap takes nothing returns nothing
    set gg_trg_Control_Swap = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Control_S=========================================
function Trig_Teleport_Conditions takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A00E' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Teleport_Actions takes nothing returns nothing
    call SetUnitPositionLoc( GetSpellAbilityUnit(), GetRectCenter(gg_rct_Shopping_Area) )
    call CameraSetupApplyForPlayer( true, gg_cam_Camera_003, GetOwningPlayer(GetSpellAbilityUnit()), 0 )
endfunction

//========s )
endfunction

//===========================================================================
// Trigger: Select
//===========================================================================
function Trig_Select_Func021A takes nothing returns nothing
    call SetPlayerAllianceStateBJ( Player(10), GetEnumPlayer(), bj_ALLIANCE_ALLIED_UNITS )
endfunction

function Trig_Select_Func022A takes nothing returns nothing
    call SetPlayerAllianceStateBJ( Player(11), GetEnumPlayer(), bj_ALLIANCE_ALLIED_UN_Seireitei_Flag_Func001C() ) then
        call UnitRemoveItemSwapped( GetManipulatedItem(), GetManipulatingUnit() )
        call SetItemPositionLoc( GetManipulatedItem(), GetRectCenter(gg_rct_Seiretei_Flag_Zone) )
    else
        call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_ALWAYSHINT, ( GetPlayerName(GetOwningPlayer(GetManipulatingUnit())) + " has seized the Seireitei flag. Stop him Shinigami!" ) )
    endif
endfunction

//==================================================================g_Actions takes nothing returns nothing
    if ( Trig_Arrancar_Flag_Func001C() ) then
        call UnitRemoveItemSwapped( GetManipulatedItem(), GetManipulatingUnit() )
        call SetItemPositionLoc( GetManipulatedItem(), GetRectCenter(gg_rct_Arrancar_Flag_Zone) )
    else
        call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_ALWAYSHINT, ( GetPlayerName(GetOwningPlayer(GetManipulatingUnit())) + " has seized the Arrancar flag. Stop him Arrancar!" ) )
    endif
endfunction

//===============OG_OF_WAR_VISIBLE, gg_rct_HeroSelect )
    call CreateFogModifierRectBJ( true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_Shopping_Area )
    call CameraSetupApplyForPlayer( true, gg_cam_Camera_005, GetEnumPlayer(), 0 )
endfunction

function Trig_Select_Copy_Copy_Copy_Func006A takes nothing returns nothing
    call CreateFogModifierRectBJ( true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_Region_018 )
endfunction

function Trig_Select_Copy_Copy_Copy_Func007A takes nothing returns nothing
    call call CreateFogModifierRectBJ( true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_HeroSelect )
    call CreateFogModifierRectBJ( true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_Shopping_Area )
    call CameraSetupApplyForPlayer( true, gg_cam_Camera_005, GetEnumPlayer(), 0 )
endfunction

function Trig_Select_Copy_Actions takes nothing returns nothing
    call KillUnit( GetEnteringUnit() )
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_ALWAYSHINT, ( GetPlayerName(Player(0)) + " has selectedp" )
    call MultiboardSetItemIconBJ( udg_ArenaBoard, 2, 1, "ReplaceableTextures\\CommandButtons\\BTNAvatarOff.blp" )
    call MultiboardSetItemIconBJ( udg_ArenaBoard, 1, 2, "ReplaceableTextures\\PassiveButtons\\PASBTNStatUp.blp" )
    call MultiboardSetItemIconBJ( udg_ArenaBoard, 2, 2, "ReplaceableTextures\\PassiveButtons\\PASBTNStatUp.blp" )
    call MultiboardSetItemValueBJ( udg_ArenaBoard, 1, 1, "TRIGSTR_605" )
    call MultiboardSetItemValueBJ( udg_ArenaBoard, 1, 2, ( I2S(udg_SeireiteiPoints) + "unc002002 takes nothing returns boolean
    return ( udg_GameMode == 3 )
endfunction

function Trig_Enterarea_Func006C takes nothing returns boolean
    if ( not GetBooleanAnd( Trig_Enterarea_Func006Func002001(), Trig_Enterarea_Func006Func002002() ) ) then
        return false
    endif
    return true
endfunction

function Trig_Enterarea_Func007Func002001 takes nothing returns boolean
    return ( IsUnitAlly(GetEnteringUnit(), Player(10)) == true )
endfunction

function Trig_Enterarea_Func00==
// Trigger: Heuco Mundo Enter Shin
//===========================================================================
function Trig_Heuco_Mundo_Enter_Shin_Actions takes nothing returns nothing
    call SetUnitPositionLoc( GetEnteringUnit(), GetRectCenter(gg_rct_Region_027) )
endfunction

//===========================================================================
function InitTrig_Heuco_Mundo_Enter_Shin takes nothing returns nothing
    set gg_trg_Heuco_Mundo_Enter_Shin = CreateTrigger(  )
    call   return true
endfunction

function Trig_Dies_Func002Func004Func004001 takes nothing returns boolean
    return ( IsUnitAlly(GetKillingUnitBJ(), Player(11)) == true )
endfunction

function Trig_Dies_Func002Func004Func004002 takes nothing returns boolean
    return ( IsUnitAlly(GetDyingUnit(), Player(11)) == true )
endfunction

function Trig_Dies_Func002Func004C takes nothing returns boolean
    if ( not GetBooleanAnd( Trig_Dies_Func002Func004Func004001(), Trig_Dies_Func002Func004Func004002() ) ion Trig_Dies_Func003Func005Func005C takes nothing returns boolean
    if ( not ( udg_ArrancarPoints >= 110 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Dies_Func003Func005Func006001 takes nothing returns boolean
    return ( IsUnitAlly(GetKillingUnitBJ(), Player(11)) == true )
endfunction

function Trig_Dies_Func003Func005Func006002 takes nothing returns boolean
    return ( IsUnitAlly(GetDyingUnit(), Player(10)) == true )
endfunction

function Trig_DiesssageBJ( GetPlayersAll(), bj_QUESTMESSAGE_ALWAYSHINT, ( ( GetPlayerName(GetOwningPlayer(GetDyingUnit())) + " has been defeaten by " ) + ( GetPlayerName(GetOwningPlayer(GetKillingUnitBJ())) + " this was however a team kill, so Seireitei lose one point." ) ) )
            set udg_SeireiteiPoints = ( udg_SeireiteiPoints - 1 )
            call MultiboardSetItemValueBJ( udg_ArenaBoard, 1, 2, ( I2S(udg_SeireiteiPoints) + " Points" ) )
        else
        endif
        if ( Trig_Dies_Func003Func003C() ) thenlayerEventLeave( gg_trg_Player_Leaves, Player(0) )
    call TriggerAddAction( gg_trg_Player_Leaves, function Trig_Player_Leaves_Actions )
endfunction

//===========================================================================
// Trigger: Player Leaves Copy
//===========================================================================
function Trig_Player_Leaves_Copy_Actions takes nothing returns nothing
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_ALWAYSHINT, ( GetPlayerName(GetTriggeventLeave( gg_trg_Player_Leaves_Copy_5, Player(5) )
    call TriggerAddAction( gg_trg_Player_Leaves_Copy_5, function Trig_Player_Leaves_Copy_5_Actions )
endfunction

//===========================================================================
// Trigger: Player Leaves Copy 6
//===========================================================================
function Trig_Player_Leaves_Copy_6_Actions takes nothing returns nothing
    call QuestMessageBJ( GetPlayersAll(), bj_QUESTMESSAGE_ALWAYSHINT, ( GetPhing returns nothing
    set gg_trg_Income = CreateTrigger(  )
    call TriggerRegisterTimerEventPeriodic( gg_trg_Income, 60.00 )
    call TriggerAddAction( gg_trg_Income, function Trig_Income_Actions )
endfunction

//===========================================================================
// Trigger: Tozansho
//===========================================================================
function Trig_Tozansho_Conditions takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A00S' _Goc_Group )
    // Cast
    set bj_forLoopAIndex = 1
    set bj_forLoopAIndexEnd = 5
    loop
        exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
        set udg_Goc_Point[2] = PolarProjectionBJ(udg_Goc_Point[1], udg_Goc_Aoe, ( 72.00 * I2R(GetForLoopIndexA()) ))
        call CreateNUnitsAtLoc( 1, 'h012', GetOwningPlayer(udg_Goc_Caster), udg_Goc_Point[2], bj_UNIT_FACING )
        set udg_Goc_Dummy = GetLastCreatedUnit()
        call GroupAddUnitSimple( udg_Goc_Dummy, udg_Goc_Group )
        seudg_D_Point[1])
        set udg_D = udg_D + 1
    endloop
    call ForGroupBJ( udg_D_Group, function Trig_Danku_Summon_Func013A )
    call GroupClear( udg_D_Group )
    call DestroyGroup(udg_D_Group)
    call RemoveLocation(udg_D_Point[0])
endfunction

//===========================================================================
function InitTrig_Danku_Summon takes nothing returns nothing
    set gg_trg_Danku_Summon = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Danku_Summon,   set udg_KB_GeneralIntegers[1] = ( udg_KB_GeneralIntegers[1] - 1 )
        else
        endif
        set udg_KB_Units[udg_KB_TotalKnockUnits] = null
        set udg_KB_TotalKnockUnits = ( udg_KB_TotalKnockUnits - 1 )
        if ( Trig_Cast_A_Knockback_Func001Func007C() ) then
            set udg_KB_TotalKnockUnits = 0
            call DisableTrigger( gg_trg_Get_Knockback )
        else
        endif
    else
    endif
    if ( Trig_Cast_A_Knockback_Func002C() ) then
        call EnableTrigge false
    endif
    return true
endfunction

function Trig_Get_Knockback_Func001Func001C takes nothing returns boolean
    if ( not ( IsUnitInGroup(udg_KB_Units[udg_KB_GeneralIntegers[1]], udg_KB_KnockbackedUnits) == true ) ) then
        return false
    endif
    return true
endfunction

function Trig_Get_Knockback_Actions takes nothing returns nothing
    set udg_KB_GeneralIntegers[1] = 1
    loop
        exitwhen udg_KB_GeneralIntegers[1] > udg_KB_TotalKnockUnits
        if ( Trig_Get_K_Get_Knockback_Func001Func001Func002Func015C() ) then
                    set udg_KB_EffectCounter[udg_KB_GeneralIntegers[1]] = 0
                    call AddSpecialEffectLocBJ( udg_KB_TempPoint[1], udg_KB_Effects_1[udg_KB_GeneralIntegers[1]] )
                    call DestroyEffectBJ( GetLastCreatedEffectBJ() )
                else
                endif
                if ( Trig_Get_Knockback_Func001Func001Func002Func016C() ) then
                    set udg_KB_EffectCounter2[udg_KB_GeneralIntegers[nc004002003002001 takes nothing returns boolean
    return ( IsUnitType(GetFilterUnit(), UNIT_TYPE_MAGIC_IMMUNE) == false )
endfunction

function Trig_Sample_Explosion_Spell_Func004002003002002001 takes nothing returns boolean
    return ( IsUnitAliveBJ(GetFilterUnit()) == true )
endfunction

function Trig_Sample_Explosion_Spell_Func004002003002002002 takes nothing returns boolean
    return ( IsUnitEnemy(GetFilterUnit(), GetOwningPlayer(GetTriggerUnit())) == true )
endfunction

function Trig_Sa)
endfunction

function Trig_Sample_Warstomp_Spell_Func004002003002001 takes nothing returns boolean
    return ( IsUnitType(GetFilterUnit(), UNIT_TYPE_MAGIC_IMMUNE) == false )
endfunction

function Trig_Sample_Warstomp_Spell_Func004002003002002001 takes nothing returns boolean
    return ( IsUnitAliveBJ(GetFilterUnit()) == true )
endfunction

function Trig_Sample_Warstomp_Spell_Func004002003002002002 takes nothing returns boolean
    return ( IsUnitEnemy(GetFilterUnit(), GetOwningPlayer(GetTrigc001Func005C takes nothing returns boolean
    if ( not ( GetUnitTypeId(udg_TempProjectile) == 'h01S' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Projectile_System_Func001Func001Func006C takes nothing returns boolean
    if ( not ( GetUnitTypeId(udg_TempProjectile) == 'h01T' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Projectile_System_Func001Func001Func007C takes nothing returns boolean
    if ( not ( GetUnitTypeId   endif
    return true
endfunction

function Trig_Projectile_System_Func001Func001Func024C takes nothing returns boolean
    if ( not ( GetUnitTypeId(udg_TempProjectile) == 'h00P' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Projectile_System_Func001Func001Func025C takes nothing returns boolean
    if ( not ( GetUnitTypeId(udg_TempProjectile) == 'h00T' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Projectile_Systenction

function Trig_Projectile_System_Func001Func001Func032Func004Func001002003 takes nothing returns boolean
    return ( IsUnitAliveBJ(GetFilterUnit()) == true )
endfunction

function Trig_Projectile_System_Func001Func001Func032Func004Func002A takes nothing returns nothing
    call UnitDamageTargetBJ( udg_TempProjectile, GetEnumUnit(), 55.00, ATTACK_TYPE_MELEE, DAMAGE_TYPE_NORMAL )
endfunction

function Trig_Projectile_System_Func001Func001Func032Func004C takes nothing returns boolean
    if nitAliveBJ(GetFilterUnit()) == true )
endfunction

function Trig_Projectile_System_Func001Func001Func032Func009Func002A takes nothing returns nothing
    call UnitDamageTargetBJ( udg_TempProjectile, GetEnumUnit(), 28.00, ATTACK_TYPE_MELEE, DAMAGE_TYPE_NORMAL )
endfunction

function Trig_Projectile_System_Func001Func001Func032Func009C takes nothing returns boolean
    if ( not ( GetUnitTypeId(udg_TempProjectile) == 'h020' ) ) then
        return false
    endif
    return true
endfunction

functurn true
endfunction

function Trig_Projectile_System_Func001Func001Func032Func014Func001002003 takes nothing returns boolean
    return ( IsUnitAliveBJ(GetFilterUnit()) == true )
endfunction

function Trig_Projectile_System_Func001Func001Func032Func014Func002A takes nothing returns nothing
    call CreateNUnitsAtLoc( 1, 'h01G', udg_TempOwner, udg_TempPoint2, bj_UNIT_FACING )
    set udg_TempDummyProjectile = GetLastCreatedUnit()
    call UnitApplyTimedLifeBJ( 5.00, 'BTLF', udg_TempDummyProjectilnction Trig_Projectile_System_Func001Func001Func032Func020Func001002003 takes nothing returns boolean
    return ( IsUnitAliveBJ(GetFilterUnit()) == true )
endfunction

function Trig_Projectile_System_Func001Func001Func032Func020Func002A takes nothing returns nothing
    call UnitDamageTargetBJ( udg_TempProjectile, GetEnumUnit(), 10.00, ATTACK_TYPE_MELEE, DAMAGE_TYPE_NORMAL )
endfunction

function Trig_Projectile_System_Func001Func001Func032Func020C takes nothing returns boolean
    if ( not ( GetUnc032Func025Func001002003 takes nothing returns boolean
    return ( IsUnitAliveBJ(GetFilterUnit()) == true )
endfunction

function Trig_Projectile_System_Func001Func001Func032Func025Func002A takes nothing returns nothing
    call CreateNUnitsAtLoc( 1, 'h02Q', udg_TempOwner, udg_TempPoint2, bj_UNIT_FACING )
    set udg_TempDummyProjectile = GetLastCreatedUnit()
    call UnitApplyTimedLifeBJ( 5.00, 'BTLF', udg_TempDummyProjectile )
    call IssueTargetOrderBJ( udg_TempDummyProjectile, "slow", GetEnum        call SetUnitLifeBJ( udg_TempProjectile, ( GetUnitStateSwap(UNIT_STATE_LIFE, udg_TempProjectile) - 5.00 ) )
        else
        endif
        if ( Trig_Projectile_System_Func001Func001Func009C() ) then
            set udg_TempPoint1 = GetUnitLoc(udg_TempProjectile)
            set udg_TempPoint2 = PolarProjectionBJ(udg_TempPoint1, 25.00, GetUnitFacing(GetEnumUnit()))
            call SetUnitPositionLoc( udg_TempProjectile, udg_TempPoint2 )
            call SetUnitLifeBJ( udg_TempProjectile, ( call DestroyEffectBJ( GetLastCreatedEffectBJ() )
            call RemoveLocation(udg_TempRand)
        else
        endif
        if ( Trig_Projectile_System_Func001Func001Func015C() ) then
            set udg_TempPoint1 = GetUnitLoc(udg_TempProjectile)
            set udg_TempPoint2 = PolarProjectionBJ(udg_TempPoint1, 35.00, GetUnitFacing(GetEnumUnit()))
            call SetUnitPositionLoc( udg_TempProjectile, udg_TempPoint2 )
            call SetUnitLifeBJ( udg_TempProjectile, ( GetUnitStateSwap(PolarProjectionBJ(udg_TempPoint1, 33.00, GetUnitFacing(GetEnumUnit()))
            call SetUnitPositionLoc( udg_TempProjectile, udg_TempPoint2 )
            call SetUnitLifeBJ( udg_TempProjectile, ( GetUnitStateSwap(UNIT_STATE_LIFE, udg_TempProjectile) - 5.00 ) )
        else
        endif
        if ( Trig_Projectile_System_Func001Func001Func023C() ) then
            set udg_TempPoint1 = GetUnitLoc(udg_TempProjectile)
            set udg_TempPoint2 = PolarProjectionBJ(udg_TempPoint1, 35.00, GetUnitFpProjectile, udg_TempPoint2 )
            call SetUnitLifeBJ( udg_TempProjectile, ( GetUnitStateSwap(UNIT_STATE_LIFE, udg_TempProjectile) - 5.00 ) )
        else
        endif
        if ( Trig_Projectile_System_Func001Func001Func030C() ) then
            set udg_TempPoint1 = GetUnitLoc(udg_TempProjectile)
            set udg_TempPoint2 = PolarProjectionBJ(udg_TempPoint1, 30.00, GetUnitFacing(GetEnumUnit()))
            call SetUnitPositionLoc( udg_TempProjectile, udg_TempPoint2 )
            call SDamageGroup = GetUnitsInRangeOfLocMatching(75.00, udg_TempPoint2, Condition(function Trig_Projectile_System_Func001Func001Func032Func007Func001002003))
                call ForGroupBJ( udg_DamageGroup, function Trig_Projectile_System_Func001Func001Func032Func007Func002A )
                call KillUnit( udg_TempProjectile )
                call DestroyGroup(udg_DamageGroup)
            else
            endif
            if ( Trig_Projectile_System_Func001Func001Func032Func008C() ) then
               e_System_Func001Func001Func032Func015C() ) then
                set udg_DamageGroup = GetUnitsInRangeOfLocMatching(75.00, udg_TempPoint2, Condition(function Trig_Projectile_System_Func001Func001Func032Func015Func001002003))
                call ForGroupBJ( udg_DamageGroup, function Trig_Projectile_System_Func001Func001Func032Func015Func002A )
                call KillUnit( udg_TempProjectile )
                call DestroyGroup(udg_DamageGroup)
            else
            endif
            if ( Trig_p)
            else
            endif
            if ( Trig_Projectile_System_Func001Func001Func032Func023C() ) then
                set udg_DamageGroup = GetUnitsInRangeOfLocMatching(75.00, udg_TempPoint2, Condition(function Trig_Projectile_System_Func001Func001Func032Func023Func001002003))
                call ForGroupBJ( udg_DamageGroup, function Trig_Projectile_System_Func001Func001Func032Func023Func002A )
                call KillUnit( udg_TempProjectile )
                call DestroyGroup(udg_Dtakes nothing returns boolean
    if ( not ( GetUnitTypeId(udg_ProjectileDeath) == 'h00L' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Projectile_Death_System_Func001Func012C takes nothing returns boolean
    if ( not ( GetUnitTypeId(udg_ProjectileDeath) == 'h00T' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Projectile_Death_System_Func001Func013C takes nothing returns boolean
    if ( not ( GetUnitTypeId(udg_Projecti_forLoopAIndex = 1
            set bj_forLoopAIndexEnd = 3
            loop
                exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
                set udg_Ring = PolarProjectionBJ(udg_TempPoint6, 40.00, ( 120.00 * I2R(GetForLoopIndexA()) ))
                call AddSpecialEffectLocBJ( udg_Ring, "war3mapImported\\NewGroundEX.mdx" )
                call DestroyEffectBJ( GetLastCreatedEffectBJ() )
                call RemoveLocation(udg_Ring)
                set bj_forLoopAIndex = bj_forLoopAIn1Func010C() ) then
            set bj_forLoopAIndex = 1
            set bj_forLoopAIndexEnd = 3
            loop
                exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
                set udg_Ring = PolarProjectionBJ(udg_TempPoint6, 40.00, ( 120.00 * I2R(GetForLoopIndexA()) ))
                call AddSpecialEffectLocBJ( udg_Ring, "Abilities\\Spells\\Orc\\FeralSpirit\\feralspirittarget.mdl" )
                call DestroyEffectBJ( GetLastCreatedEffectBJ() )
                call RemoveLocationl PlaySoundAtPointBJ( gg_snd_SoulPreservation, 100, udg_TempPoint6, 0 )
            call RemoveLocation(udg_TempPoint6)
        else
        endif
        if ( Trig_Projectile_Death_System_Func001Func015C() ) then
            set bj_forLoopAIndex = 1
            set bj_forLoopAIndexEnd = 5
            loop
                exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
                set udg_Ring = PolarProjectionBJ(udg_TempPoint6, 40.00, ( 72.00 * I2R(GetForLoopIndexA()) ))
                call opAIndex = 1
            set bj_forLoopAIndexEnd = 5
            loop
                exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
                set udg_Ring = PolarProjectionBJ(udg_TempPoint6, 40.00, ( 72.00 * I2R(GetForLoopIndexA()) ))
                call AddSpecialEffectLocBJ( udg_Ring, "Abilities\\Spells\\Other\\FrostBolt\\FrostBoltMissile.mdl" )
                call DestroyEffectBJ( GetLastCreatedEffectBJ() )
                call RemoveLocation(udg_Ring)
                set bj_forLoopAInd               call AddSpecialEffectLocBJ( udg_Ring, "Abilities\\Spells\\Other\\Stampede\\StampedeMissileDeath.mdl" )
                call DestroyEffectBJ( GetLastCreatedEffectBJ() )
                call RemoveLocation(udg_Ring)
                set bj_forLoopAIndex = bj_forLoopAIndex + 1
            endloop
            call AddSpecialEffectLocBJ( udg_TempPoint6, "Objects\\Spawnmodels\\Undead\\UndeadDissipate\\UndeadDissipate.mdl" )
            call DestroyEffectBJ( GetLastCreatedEffectBJ() )
        urn true
endfunction

function Trig_Effects_Loss_System_Func004C takes nothing returns boolean
    if ( not ( UnitHasBuffBJ(udg_DyingUnit, 'B005') == true ) ) then
        return false
    endif
    return true
endfunction

function Trig_Effects_Loss_System_Actions takes nothing returns nothing
    set udg_DyingUnit = GetDyingUnit()
    if ( Trig_Effects_Loss_System_Func002C() ) then
        call UnitRemoveAbilityBJ( 'A010', udg_DyingUnit )
        call UnitRemoveAbilityBJ( 'A01K', udg_Caster sAtLoc( 1, 'h01X', udg_TempZanOwner, udg_TempZanPoint1, bj_UNIT_FACING )
    set udg_TempDummyProjectile = GetLastCreatedUnit()
    call UnitApplyTimedLifeBJ( 1.00, 'BTLF', udg_TempDummyProjectile )
    call IssueTargetOrderBJ( udg_TempDummyProjectile, "slow", GetEnumUnit() )
endfunction

function Trig_Release_Effects_System_Func001Func012C takes nothing returns boolean
    if ( not ( UnitHasBuffBJ(udg_TempZan, 'B008') == true ) ) then
        return false
    endif
    return true
endfunction
   endif
    if ( Trig_Release_Effects_System_Func001Func009C() ) then
        set udg_TempZanPoint1 = GetUnitLoc(udg_TempZan)
        set udg_TempZanPoint2 = PolarProjectionBJ(udg_TempZanPoint1, GetRandomReal(0, 300.00), GetRandomDirectionDeg())
        call AddSpecialEffectLocBJ( udg_TempZanPoint2, "Abilities\\Spells\\Undead\\DeathCoil\\DeathCoilSpecialArt.mdl" )
        call DestroyEffectBJ( GetLastCreatedEffectBJ() )
    else
    endif
    if ( Trig_Release_Effects_System_Func001Func010C() ) thection Trig_Effectgroupcheck_Func001Func003C takes nothing returns boolean
    if ( not ( UnitHasBuffBJ(udg_TempKyo, 'B007') == true ) ) then
        return false
    endif
    return true
endfunction

function Trig_Effectgroupcheck_Func001Func004C takes nothing returns boolean
    if ( not ( UnitHasBuffBJ(udg_TempKyo, 'B00V') == true ) ) then
        return false
    endif
    return true
endfunction

function Trig_Effectgroupcheck_Func001Func005C takes nothing returns boolean
    if ( not ( groupcheck_Func001Func007C() ) then
    else
        call UnitRemoveAbilityBJ( 'A031', udg_TempKyo )
        call UnitRemoveAbilityBJ( 'A01G', udg_TempKyo )
    endif
    if ( Trig_Effectgroupcheck_Func001Func008C() ) then
    else
        call UnitRemoveAbilityBJ( 'A015', udg_TempKyo )
        call UnitRemoveAbilityBJ( 'A01O', udg_TempKyo )
    endif
    if ( Trig_Effectgroupcheck_Func001Func009C() ) then
    else
        call UnitRemoveAbilityBJ( 'A01V', udg_TempKyo )
        call UnitRemoveAAction( gg_trg_Summons_Remove, function Trig_Summons_Remove_Actions )
endfunction

//===========================================================================
// Trigger: Garganta
//===========================================================================
function Trig_Garganta_Conditions takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A02J' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Garganta_Func001C takes nothing returns booleanreturns nothing
    call UnitApplyTimedLifeBJ( 10.00, 'BTLF', GetEnumUnit() )
endfunction

function Trig_Senkaimon_Actions takes nothing returns nothing
    if ( Trig_Senkaimon_Func001C() ) then
        call SetUnitAnimation( udg_Caster, "spell" )
    else
    endif
    set udg_Caster = GetSpellAbilityUnit()
    set udg_TempLoc1 = GetSpellTargetLoc()
    set udg_TempLoc2 = GetSpellTargetLoc()
    set udg_TempLoc3 = PolarProjectionBJ(udg_TempLoc1, 30.00, AngleBetweenPoints(udg_TempPoint1, udg_Tem_SPELL_EFFECT )
    call TriggerAddCondition( gg_trg_Hougyoku, Condition( function Trig_Hougyoku_Conditions ) )
    call TriggerAddAction( gg_trg_Hougyoku, function Trig_Hougyoku_Actions )
endfunction

//===========================================================================
// Trigger: Negacion
//===========================================================================
function Trig_Negacion_Conditions takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A02A' ) ) then
     Trig_Teleport_Seireitei takes nothing returns nothing
    set gg_trg_Teleport_Seireitei = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Teleport_Seireitei, EVENT_PLAYER_UNIT_SPELL_EFFECT )
    call TriggerAddCondition( gg_trg_Teleport_Seireitei, Condition( function Trig_Teleport_Seireitei_Conditions ) )
    call TriggerAddAction( gg_trg_Teleport_Seireitei, function Trig_Teleport_Seireitei_Actions )
endfunction

//=====================================================================AngleBetweenPoints(udg_TempLoc1, udg_TempLoc5) )
    set udg_TempDummyProjectile = GetLastCreatedUnit()
    call GroupAddUnitSimple( udg_TempDummyProjectile, udg_Ball_Group )
    call RemoveLocation(udg_TempLoc1)
    call RemoveLocation(udg_TempLoc2)
    call RemoveLocation(udg_TempLoc3)
    call RemoveLocation(udg_TempLoc4)
    call RemoveLocation(udg_TempLoc5)
endfunction

//===========================================================================
function InitTrig_Raikouhou_Cast takes nothin       call CreateNUnitsAtLoc( 1, 'h009', GetOwningPlayer(udg_Caster), udg_TempRing, AngleBetweenPoints(udg_TempLoc1, udg_TempRing) )
        set udg_TempDummyProjectile = GetLastCreatedUnit()
        call GroupAddUnitSimple( udg_TempDummyProjectile, udg_Ball_Group )
        call RemoveLocation(udg_TempRing)
        set bj_forLoopBIndex = bj_forLoopBIndex + 1
    endloop
    call RemoveLocation(udg_TempLoc1)
    call RemoveLocation(udg_TempLoc2)
endfunction

//===================================== ( Trig_Bankin_New_Cast_Func001C() ) then
        call SetUnitAnimation( udg_Caster, "spell" )
    else
    endif
    set udg_Caster = GetSpellAbilityUnit()
    set udg_TempLoc1 = GetSpellTargetLoc()
    set udg_Darkness_Group = GetUnitsInRangeOfLocAll(500.00, udg_TempLoc1)
    call CreateNUnitsAtLoc( 1, 'h00N', GetOwningPlayer(udg_Caster), udg_TempLoc1, bj_UNIT_FACING )
    set udg_TempDummyProp = GetLastCreatedUnit()
    call UnitApplyTimedLifeBJ( 1.00, 'BTLF', udg_TempDummyProp )
    call SetUnro_Blast_Cast_Func002C() ) then
        call SetUnitAnimation( udg_Caster, "spell" )
    else
    endif
    set udg_Caster = GetSpellAbilityUnit()
    set udg_TempLoc1 = GetUnitLoc(udg_Caster)
    set udg_TempLoc2 = GetSpellTargetLoc()
    set udg_TempLoc3 = PolarProjectionBJ(udg_TempLoc1, 30.00, AngleBetweenPoints(udg_TempPoint1, udg_TempLoc3))
    call PlaySoundAtPointBJ( gg_snd_Cero_Sound, 100, udg_TempLoc1, 0 )
    call CreateNUnitsAtLoc( 1, 'h00T', GetOwningPlayer(udg_Caster), udg_TempLoc3, Andg_TempLoc1 = GetUnitLoc(udg_Caster)
    set udg_TempLoc2 = GetSpellTargetLoc()
    set udg_TempLoc3 = PolarProjectionBJ(udg_TempLoc1, 30.00, AngleBetweenPoints(udg_TempPoint1, udg_TempLoc3))
    set udg_TempLoc4 = PolarProjectionBJ(udg_TempLoc1, 30.00, ( AngleBetweenPoints(udg_TempLoc1, udg_TempLoc2) + 15.00 ))
    set udg_TempLoc5 = PolarProjectionBJ(udg_TempLoc1, 30.00, ( AngleBetweenPoints(udg_TempLoc1, udg_TempLoc2) + 345.00 ))
    call CreateNUnitsAtLoc( 1, 'h018', GetOwningPlayer(udg_Caster), ud====================================
// Trigger: Soren Sokatsui Cast
//===========================================================================
function Trig_Soren_Sokatsui_Cast_Conditions takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A00X' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Soren_Sokatsui_Cast_Func001C takes nothing returns boolean
    if ( not ( IsUnitAliveBJ(udg_Caster) == true ) ) then
        return false
    endif
 ) then
        return false
    endif
    return true
endfunction

function Trig_Itto_Kaso_Func008002003 takes nothing returns boolean
    return ( IsUnitEnemy(GetFilterUnit(), GetOwningPlayer(udg_Caster)) == true )
endfunction

function Trig_Itto_Kaso_Func009A takes nothing returns nothing
    call UnitDamageTargetBJ( udg_Caster, GetEnumUnit(), 75.00, ATTACK_TYPE_HERO, DAMAGE_TYPE_NORMAL )
endfunction

function Trig_Itto_Kaso_Actions takes nothing returns nothing
    if ( Trig_Itto_Kaso_Funthing returns nothing
    call SetUnitManaBJ( GetEnumUnit(), ( GetUnitStateSwap(UNIT_STATE_MANA, GetEnumUnit()) + 4.00 ) )
    call SetUnitScalePercent( GetEnumUnit(), ( 100.00 + ( GetUnitStateSwap(UNIT_STATE_MANA, GetEnumUnit()) * 2.00 ) ), ( 100.00 + ( GetUnitStateSwap(UNIT_STATE_MANA, GetEnumUnit()) * 2.00 ) ), ( 100.00 + ( GetUnitStateSwap(UNIT_STATE_MANA, GetEnumUnit()) * 2.00 ) ) )
endfunction

function Trig_Growth_Actions takes nothing returns nothing
    call ForGroupBJ( udg_BallPowerGroup, fu then
        return false
    endif
    return true
endfunction

function Trig_Kuro_Cast_Func001C takes nothing returns boolean
    if ( not ( udg_Kuro_Skip == 0 ) ) then
        return false
    endif
    return true
endfunction

function Trig_Kuro_Cast_Actions takes nothing returns nothing
    if ( Trig_Kuro_Cast_Func001C() ) then
        call EnableTrigger( gg_trg_Kuro_Loop )
    else
    endif
    set udg_Kuro_Times = ( udg_Kuro_Times + 1 )
    set udg_Kuro_Skip = ( udg_Kuro_Skip + 1001Func003002003002002() )
endfunction

function Trig_Kuro_Loop_Func001Func001Func001Func003002003 takes nothing returns boolean
    return GetBooleanAnd( Trig_Kuro_Loop_Func001Func001Func001Func003002003001(), Trig_Kuro_Loop_Func001Func001Func001Func003002003002() )
endfunction

function Trig_Kuro_Loop_Func001Func001Func001Func004A takes nothing returns nothing
    call AddSpecialEffectLocBJ( udg_Kuro_Point[2], "Abilities\\Spells\\Undead\\DeathCoil\\DeathCoilSpecialArt.mdl" )
    call DestroyEffec================================================================
function Trig_Kyouka_Suigetsu_Conditions takes nothing returns boolean
    if ( not ( GetItemTypeId(GetManipulatedItem()) == 'I006' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Kyouka_Suigetsu_Actions takes nothing returns nothing
    call UnitAddAbilityBJ( 'A01E', GetManipulatingUnit() )
    call SetUnitPositionLoc( GetManipulatingUnit(), GetRectCenter(gg_rct_Shopping_Area) )
    call RemoveItection InitTrig_Suzumushi takes nothing returns nothing
    set gg_trg_Suzumushi = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Suzumushi, EVENT_PLAYER_UNIT_PICKUP_ITEM )
    call TriggerAddCondition( gg_trg_Suzumushi, Condition( function Trig_Suzumushi_Conditions ) )
    call TriggerAddAction( gg_trg_Suzumushi, function Trig_Suzumushi_Actions )
endfunction

//===========================================================================
// Trigger: Tiburon
//=======================   endif
    return true
endfunction

function Trig_Ashisoji_Jizou_Actions takes nothing returns nothing
    call UnitAddAbilityBJ( 'A023', GetManipulatingUnit() )
    call SetUnitPositionLoc( GetManipulatingUnit(), GetRectCenter(gg_rct_Shopping_Area) )
    call RemoveItem( GetManipulatedItem() )
endfunction

//===========================================================================
function InitTrig_Ashisoji_Jizou takes nothing returns nothing
    set gg_trg_Ashisoji_Jizou = CreateTrigger(   function Trig_Gamuza_Conditions ) )
    call TriggerAddAction( gg_trg_Gamuza, function Trig_Gamuza_Actions )
endfunction

//===========================================================================
// Trigger: Shinso
//===========================================================================
function Trig_Shinso_Conditions takes nothing returns boolean
    if ( not ( GetItemTypeId(GetManipulatedItem()) == 'I013' ) ) then
        return false
    endif
    return true
endfunction

function    call TriggerAddCondition( gg_trg_Kyouka_Suigetsu_Release, Condition( function Trig_Kyouka_Suigetsu_Release_Conditions ) )
    call TriggerAddAction( gg_trg_Kyouka_Suigetsu_Release, function Trig_Kyouka_Suigetsu_Release_Actions )
endfunction

//===========================================================================
// Trigger: Effect
//===========================================================================
function Trig_Effect_Conditions takes nothing returns boolean
    if ( not ( GetSpeall CreateNUnitsAtLoc( 1, 'h01A', GetOwningPlayer(udg_Caster), udg_TempRing, AngleBetweenPoints(udg_TempLoc1, udg_TempRing) )
        set udg_TempDummyProjectile = GetLastCreatedUnit()
        call GroupAddUnitSimple( udg_TempDummyProjectile, udg_Ball_Group )
        call RemoveLocation(udg_TempRing)
        set bj_forLoopBIndex = bj_forLoopBIndex + 1
    endloop
    set udg_KyouGroup = GetUnitsInRangeOfLocMatching(400.00, udg_TempLoc1, Condition(function Trig_Kyouka_Emerge_Func006002003))
    call F=========================
// Trigger: Ryujin Jakka Release
//===========================================================================
function Trig_Ryujin_Jakka_Release_Func001C takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A01C' ) ) then
        return false
    endif
    if ( not ( UnitHasBuffBJ(GetSpellAbilityUnit(), 'B007') == false ) ) then
        return false
    endif
    return true
endfunction

function Trig_Ryujin_Jakka_Release_Conditions takes nothing returveLocation(udg_TempLoc1)
endfunction

//===========================================================================
function InitTrig_Jokkako_Enjou_Cast takes nothing returns nothing
    set gg_trg_Jokkako_Enjou_Cast = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Jokkako_Enjou_Cast, EVENT_PLAYER_UNIT_SPELL_EFFECT )
    call TriggerAddCondition( gg_trg_Jokkako_Enjou_Cast, Condition( function Trig_Jokkako_Enjou_Cast_Conditions ) )
    call TriggerAddAction( gg_trg_Jokkako_Enjou_Casrogantes_Release takes nothing returns nothing
    set gg_trg_Arrogantes_Release = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Arrogantes_Release, EVENT_PLAYER_UNIT_SPELL_EFFECT )
    call TriggerAddCondition( gg_trg_Arrogantes_Release, Condition( function Trig_Arrogantes_Release_Conditions ) )
    call TriggerAddAction( gg_trg_Arrogantes_Release, function Trig_Arrogantes_Release_Actions )
endfunction

//===========================================================================gisterAnyUnitEventBJ( gg_trg_Gran_Caida_Cast, EVENT_PLAYER_UNIT_SPELL_EFFECT )
    call TriggerAddCondition( gg_trg_Gran_Caida_Cast, Condition( function Trig_Gran_Caida_Cast_Conditions ) )
    call TriggerAddAction( gg_trg_Gran_Caida_Cast, function Trig_Gran_Caida_Cast_Actions )
endfunction

//===========================================================================
// Trigger: Suzumushi Release
//===========================================================================
function Trig_Suzumushi_Rfunction Trig_Benihikou_Conditions ) )
    call TriggerAddAction( gg_trg_Benihikou, function Trig_Benihikou_Actions )
endfunction

//===========================================================================
// Trigger: Enma Korogi Cast
//===========================================================================
function Trig_Enma_Korogi_Cast_Conditions takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A031' ) ) then
        return false
    endif
    return true
endfunctioning returns nothing
    set udg_ZanCaster = GetSpellAbilityUnit()
    set udg_TempLoc1 = GetUnitLoc(udg_ZanCaster)
    call GroupAddUnitSimple( udg_ZanCaster, udg_FallGroup )
    call GroupAddUnitSimple( udg_ZanCaster, udg_KyoukaEffectGroup )
    call UnitAddAbilityBJ( 'A015', udg_ZanCaster )
    call UnitAddAbilityBJ( 'A01O', udg_ZanCaster )
    call CreateTextTagLocBJ( "TRIGSTR_1099", udg_TempLoc1, 0, 10, 100, 100, 100, 0 )
    set udg_TempText = GetLastCreatedTextTag()
    call SetTextTagPermaneTrig_La_Gota_Cast_Conditions takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A01O' ) ) then
        return false
    endif
    return true
endfunction

function Trig_La_Gota_Cast_Func001C takes nothing returns boolean
    if ( not ( IsUnitAliveBJ(udg_Caster) == true ) ) then
        return false
    endif
    return true
endfunction

function Trig_La_Gota_Cast_Actions takes nothing returns nothing
    if ( Trig_La_Gota_Cast_Func001C() ) then
        call SetUnitAnimation( IsUnitAliveBJ(udg_Caster) == true ) ) then
        return false
    endif
    return true
endfunction

function Trig_Cero_Oscuras_cast_Actions takes nothing returns nothing
    if ( Trig_Cero_Oscuras_cast_Func001C() ) then
        call SetUnitAnimation( udg_Caster, "spell" )
    else
    endif
    set udg_Caster = GetSpellAbilityUnit()
    set udg_TempLoc1 = GetUnitLoc(udg_Caster)
    set udg_TempLoc2 = GetSpellTargetLoc()
    set udg_TempLoc3 = PolarProjectionBJ(udg_TempLoc1, 30.00, AngleBenditions takes nothing returns boolean
    if ( not Trig_Minazuki_Release_Func001C() ) then
        return false
    endif
    return true
endfunction

function Trig_Minazuki_Release_Actions takes nothing returns nothing
    set udg_ZanCaster = GetSpellAbilityUnit()
    set udg_TempLoc1 = GetUnitLoc(udg_ZanCaster)
    call CreateNUnitsAtLoc( 1, 'h022', GetOwningPlayer(udg_ZanCaster), udg_TempLoc1, GetUnitFacing(udg_ZanCaster) )
    set udg_MinazukiTemp = GetLastCreatedUnit()
    call UnitApplyTindif
    return true
endfunction

function Trig_Minazuki_Land_Func005A takes nothing returns nothing
    call SetUnitAnimation( GetEnumUnit(), "Walk - 2" )
    call UnitRemoveAbilityBJ( 'A022', GetEnumUnit() )
    call IssueImmediateOrderBJ( GetEnumUnit(), "stop" )
    call IssueImmediateOrderBJ( GetEnumUnit(), "healon" )
    call SetUnitFlyHeightBJ( GetEnumUnit(), 0.00, 1300.00 )
    call IssueImmediateOrderBJ( GetEnumUnit(), "healon" )
endfunction

function Trig_Minazuki_Land_Actions takes no==
function Trig_Jizou_Charge_Conditions takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A028' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Jizou_Charge_Func001C takes nothing returns boolean
    if ( not ( IsUnitAliveBJ(udg_Caster) == true ) ) then
        return false
    endif
    return true
endfunction

function Trig_Jizou_Charge_Func006A takes nothing returns nothing
    call IssuePointOrderLocBJ( GetEnumUnit(), "carrionswarm",            set bj_forLoopBIndex = bj_forLoopBIndex + 1
        endloop
        set bj_forLoopAIndex = bj_forLoopAIndex + 1
    endloop
endfunction

function Trig_Jizou_Slam_Actions takes nothing returns nothing
    if ( Trig_Jizou_Slam_Func001C() ) then
        call SetUnitAnimation( udg_Caster, "spell" )
    else
    endif
    set udg_Caster = GetSpellAbilityUnit()
    set udg_CasterOwner = GetOwningPlayer(udg_Caster)
    set udg_TempLoc1 = GetSpellTargetLoc()
    call CreateNUnitsAtLoc( 1, Jizou_Func006A )
    call RemoveLocation(udg_TempLoc1)
    call DestroyGroup(udg_MinazukiGroup2)
endfunction

//===========================================================================
function InitTrig_Follow_Jizou takes nothing returns nothing
    set gg_trg_Follow_Jizou = CreateTrigger(  )
    call TriggerRegisterAnyUnitEventBJ( gg_trg_Follow_Jizou, EVENT_PLAYER_UNIT_SPELL_EFFECT )
    call TriggerAddCondition( gg_trg_Follow_Jizou, Condition( function Trig_Follow_Jizou_Conditions ) )
    cal
    call UnitDamageTargetBJ( udg_Caster, GetEnumUnit(), 30.00, ATTACK_TYPE_MELEE, DAMAGE_TYPE_NORMAL )
endfunction

function Trig_Tengen_Slam_Func006A takes nothing returns nothing
    call SetUnitFacingToFaceLocTimed( GetEnumUnit(), udg_TempLoc1, 0 )
    call SetUnitAnimation( GetEnumUnit(), "Attack (1.170 s)" )
    set udg_TengenDamGroup1 = GetUnitsInRangeOfLocMatching(400.00, udg_TempLoc1, Condition(function Trig_Tengen_Slam_Func006Func003002003))
    call ForGroupBJ( udg_TengenDamGroup1, functingenDamGroup1, function Trig_Mega_Tengen_Slam_Func006Func003A )
    set bj_forLoopAIndex = 1
    set bj_forLoopAIndexEnd = 10
    loop
        exitwhen bj_forLoopAIndex > bj_forLoopAIndexEnd
        set bj_forLoopBIndex = 1
        set bj_forLoopBIndexEnd = 10
        loop
            exitwhen bj_forLoopBIndex > bj_forLoopBIndexEnd
            set udg_TempLoc2 = PolarProjectionBJ(udg_TempLoc1, ( 30.00 + ( I2R(GetForLoopIndexA()) * 80.00 ) ), ( 36.00 * I2R(GetForLoopIndexB()) ))
            call Ad   call TriggerAddAction( gg_trg_Calderon_Release, function Trig_Calderon_Release_Actions )
endfunction

//===========================================================================
// Trigger: Calderon Slam
//===========================================================================
function Trig_Calderon_Slam_Conditions takes nothing returns boolean
    if ( not ( GetSpellAbilityId() == 'A02H' ) ) then
        return false
    endif
    return true
endfunction

function Trig_Calderon_Slam_FDeclare_Gamuza_LOUD, 100, udg_TempLoc1, 0 )
    call UnitAddAbilityBJ( 'A02T', udg_ZanCaster )
    call UnitAddAbilityBJ( 'A02S', udg_ZanCaster )
    call GroupAddUnitSimple( udg_ZanCaster, udg_KyoukaEffectGroup )
    call GroupAddUnitSimple( udg_ZanCaster, udg_FallGroup )
    call CreateNUnitsAtLoc( 1, 'h02F', GetOwningPlayer(udg_ZanCaster), udg_TempLoc1, bj_UNIT_FACING )
    set udg_TempDummyProjectile = GetLastCreatedUnit()
    call UnitApplyTimedLifeBJ( 3.00, 'BTLF', udg_TempDummyProjectile )
  
    call PlaySoundAtPointBJ( gg_snd_Gin_Ichimarus_shikai___Shinsou, 100, udg_TempLoc1, 0 )
    call UnitAddAbilityBJ( 'A02V', udg_ZanCaster )
    call UnitAddAbilityBJ( 'A02W', udg_ZanCaster )
    call GroupAddUnitSimple( udg_ZanCaster, udg_KyoukaEffectGroup )
    call GroupAddUnitSimple( udg_ZanCaster, udg_FallGroup )
    call CreateTextTagLocBJ( "TRIGSTR_1582", udg_TempLoc1, 0, 10, 100, 100, 100, 0 )
    set udg_TempText = GetLastCreatedTextTag()
    call SetTextTagPermanentBJ( udg_TempText, fals
    set bj_forLoopBIndex = 1
    set bj_forLoopBIndexEnd = 15
    loop
        exitwhen bj_forLoopBIndex > bj_forLoopBIndexEnd
        set udg_TempRing = PolarProjectionBJ(udg_TempLoc1, 30.00, ( I2R(GetForLoopIndexB()) * 24.00 ))
        call CreateNUnitsAtLoc( 1, 'h02G', GetOwningPlayer(udg_Caster), udg_TempRing, AngleBetweenPoints(udg_TempLoc1, udg_TempRing) )
        set udg_TempDummyProjectile = GetLastCreatedUnit()
        call GroupAddUnitSimple( udg_TempDummyProjectile, udg_Ball_Group )
    
function Trig_Astounding_Spiritual_Pressure_Func005002003 takes nothing returns boolean
    return GetBooleanAnd( Trig_Astounding_Spiritual_Pressure_Func005002003001(), Trig_Astounding_Spiritual_Pressure_Func005002003002() )
endfunction

function Trig_Astounding_Spiritual_Pressure_Func006A takes nothing returns nothing
    call CreateNUnitsAtLoc( 1, 'h02K', udg_CasterOwner, udg_TempLoc2, bj_UNIT_FACING )
    set udg_TempDummyProp = GetLastCreatedUnit()
    call UnitApplyTimedLifeBJ( 2.00, 'BTLF', u  set udg_TempLoc6 = PolarProjectionBJ(udg_TempLoc1, 30.00, ( AngleBetweenPoints(udg_TempLoc1, udg_TempLoc2) + 330.00 ))
    set udg_TempLoc7 = PolarProjectionBJ(udg_TempLoc1, 30.00, ( AngleBetweenPoints(udg_TempLoc1, udg_TempLoc2) + 30.00 ))
    call CreateNUnitsAtLoc( 1, 'h004', GetOwningPlayer(udg_Caster), udg_TempLoc3, AngleBetweenPoints(udg_TempLoc1, udg_TempLoc2) )
    set udg_TempDummyProjectile = GetLastCreatedUnit()
    call GroupAddUnitSimple( udg_TempDummyProjectile, udg_Ball_Group )
    caldexEnd = 20
    loop
        exitwhen bj_forLoopBIndex > bj_forLoopBIndexEnd
        set udg_Goc_Point[3] = PolarProjectionBJ(udg_Goc_Point[1], udg_Goc_Aoe, ( 18.00 * I2R(GetForLoopIndexB()) ))
        call CreateNUnitsAtLoc( 1, 'h016', GetOwningPlayer(udg_Goc_Caster), udg_Goc_Point[3], bj_UNIT_FACING )
        set udg_Goc_BlockDummy = GetLastCreatedUnit()
        call GroupAddUnitSimple( udg_Goc_BlockDummy, udg_Goc_Group )
        set udg_Goc_BlockDummy = null
        call RemoveLocation(udg_Goc_Poer(udg_D_Caster), udg_D_Point[0], bj_UNIT_FACING )
    set udg_D_Dummy = GetLastCreatedUnit()
    call UnitApplyTimedLifeBJ( 10.00, 'BTLF', udg_D_Dummy )
    // Cast
    set udg_D = 1
    loop
        exitwhen udg_D > 20
        set udg_D_Point[1] = PolarProjectionBJ(udg_D_Point[0], udg_D_Aoe, ( 18.00 * I2R(udg_D) ))
        call CreateNUnitsAtLoc( 1, 'h016', GetOwningPlayer(udg_D_Caster), udg_D_Point[1], bj_UNIT_FACING )
        set udg_D_BlockDummy = GetLastCreatedUnit()
        call GroupAddUnitGroup )
    call GroupAddUnitSimple( udg_ZanCaster, udg_FallGroup )
    call CreateTextTagLocBJ( "TRIGSTR_1793", udg_TempLoc1, 0, 10, 100, 100, 100, 0 )
    set udg_TempText = GetLastCreatedTextTag()
    call SetTextTagPermanentBJ( udg_TempText, false )
    call SetTextTagLifespanBJ( udg_TempText, 4.00 )
    call SetTextTagVelocityBJ( udg_TempText, 64, 90 )
endfunction

//===========================================================================
function InitTrig_Benihime_Release takes nothing ritTrig_Sample_Warstomp_Spell(  )
    call InitTrig_Projectile_System(  )
    call InitTrig_Projectile_Death_System(  )
    call InitTrig_Effects_Loss_System(  )
    call InitTrig_Release_Effects_System(  )
    call InitTrig_Effectgroupcheck(  )
    call InitTrig_Summons_Remove(  )
    call InitTrig_Garganta(  )
    call InitTrig_Senkaimon(  )
    call InitTrig_Hougyoku(  )
    call InitTrig_Negacion(  )
    call InitTrig_Teleport_Seireitei(  )
    call InitTrig_Gintei(  )
    call InitTrig_RaikonvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), false )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

    // Player 1
    call SetPlayerStartLocation( Player(1), 1 )
    call ForcePlayerStartLocation( Player(1), 1 )
    call SetPlayerColor( Player(1), ConvertPlayerColor(1) )
    call SetPlayerRacePreference( Player(1), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(1), false )
    call See( Player(11), false )
    call SetPlayerController( Player(11), MAP_CONTROL_COMPUTER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_047
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerState( Player(0), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(1), 0 )
    call SetPlayerState( Player(1), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(2), 0 )
    call SetPlayerState( Player(2), PLAYER_STATE_ALLIED_VICTOR Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(10), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(2), trr(5), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(7), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(8), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(9), true )
    call SetPlayerAllianceStateVisionBJ( Player(6), Player(11), true )
    call SetPlayerAllianceStateVisionBJ( Player(7), Player(rtLocPrio( 3, 8, 9, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 4, 9 )
    call SetStartLocPrio( 4, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 2, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 3, 3, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 4, 5, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 5, 6, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 6, 7, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 7, 8, MAPDNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "CityScapeDay" )
    call SetAmbientNightSound( "CityScapeNight" )
    call SetMapMusic( "Music", true, 0 )
    call InitSounds(  )
    call CreateRegions(  )
    call CreateCameras(  )
    call CreateAllItems(  )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(